# fly.toml app configuration file generated for suhthanurista on 2023-05-31T18:58:27+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "suhthanurista"
primary_region = "arn"

[[services]]
  protocol = "tcp"
  internal_port = 5000

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 0
    method = "get"
    path = "/health"
    protocol = "http"
