# fly.toml app configuration file generated for perseesta on 2023-05-30T20:19:55+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "perseesta"
primary_region = "arn"




[[services]]
  http_checks = []
  internal_port = 5000
  protocol="tcp"

  [[services.ports]]
  handlers  = ["http"]
  port = "80"

  [[services.ports]]
  handlers  = ["tls","http"]
  port = "443"

[[services.tcp_checks]]
  grace_period = "1s"
  interval = "15s"
  restart_limit = 0
  timeout = "2s"   
