name: Health check

on:
  schedule:
    - cron: '00 3 * * *'
    
jobs:
  perform_health_check:
    runs-on: ubuntu-20.04
    steps:
    - name: Perform a health check
      uses: jtalk/url-health-check-action@v3
      with:
        url: https://suhthanurista.fly.dev/
        max-attempts: 2    
        retry-delay: 2s
  
