name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request: 
    branches: [master] 
    types: [opened, synchronize] 
      
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: build
        run: npm run build
      - name: Check style
        run: npm run eslint
      - name: run tests
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: pre check failure
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        if: failure()
        with:
          severity: error
          details: Build failed! This commit caused the problem ${{ github.event.commits[0].url }} by ${{ github.event.commits[0].committer.username }}.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}      
          
  deploy:    
    needs: [simple_deployment_pipeline]
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip')}}
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          
      - name: Deploy Success
        if: success() 
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          details: New commit ${{ github.event.commits[0].url }} by ${{ github.event.commits[0].committer.username }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}      
      
  tag_release:
    needs: [deploy]
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip') }}
    steps:   
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.66.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
